version: "3.8"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vsd.rule=Host(`vsd.thib.app`)"
      - "traefik.http.routers.vsd.entrypoints=websecure"
      - "traefik.http.routers.vsd.tls.certresolver=myresolver"
      - "traefik.http.services.vsd.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
